/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as ProfilesRouteImport } from './routes/profiles'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as HealthRouteImport } from './routes/health'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SourcesDocIdRouteImport } from './routes/sources.$docId'
import { Route as LessonsLessonIdRouteImport } from './routes/lessons.$lessonId'

const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesRoute = ProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesDocIdRoute = SourcesDocIdRouteImport.update({
  id: '/$docId',
  path: '/$docId',
  getParentRoute: () => SourcesRoute,
} as any)
const LessonsLessonIdRoute = LessonsLessonIdRouteImport.update({
  id: '/$lessonId',
  path: '/$lessonId',
  getParentRoute: () => LessonsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/jobs': typeof JobsRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/profiles': typeof ProfilesRoute
  '/sources': typeof SourcesRouteWithChildren
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/sources/$docId': typeof SourcesDocIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/jobs': typeof JobsRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/profiles': typeof ProfilesRoute
  '/sources': typeof SourcesRouteWithChildren
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/sources/$docId': typeof SourcesDocIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/jobs': typeof JobsRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/profiles': typeof ProfilesRoute
  '/sources': typeof SourcesRouteWithChildren
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/sources/$docId': typeof SourcesDocIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/jobs'
    | '/lessons'
    | '/profiles'
    | '/sources'
    | '/lessons/$lessonId'
    | '/sources/$docId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/jobs'
    | '/lessons'
    | '/profiles'
    | '/sources'
    | '/lessons/$lessonId'
    | '/sources/$docId'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/jobs'
    | '/lessons'
    | '/profiles'
    | '/sources'
    | '/lessons/$lessonId'
    | '/sources/$docId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  JobsRoute: typeof JobsRoute
  LessonsRoute: typeof LessonsRouteWithChildren
  ProfilesRoute: typeof ProfilesRoute
  SourcesRoute: typeof SourcesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles': {
      id: '/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$docId': {
      id: '/sources/$docId'
      path: '/$docId'
      fullPath: '/sources/$docId'
      preLoaderRoute: typeof SourcesDocIdRouteImport
      parentRoute: typeof SourcesRoute
    }
    '/lessons/$lessonId': {
      id: '/lessons/$lessonId'
      path: '/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof LessonsLessonIdRouteImport
      parentRoute: typeof LessonsRoute
    }
  }
}

interface LessonsRouteChildren {
  LessonsLessonIdRoute: typeof LessonsLessonIdRoute
}

const LessonsRouteChildren: LessonsRouteChildren = {
  LessonsLessonIdRoute: LessonsLessonIdRoute,
}

const LessonsRouteWithChildren =
  LessonsRoute._addFileChildren(LessonsRouteChildren)

interface SourcesRouteChildren {
  SourcesDocIdRoute: typeof SourcesDocIdRoute
}

const SourcesRouteChildren: SourcesRouteChildren = {
  SourcesDocIdRoute: SourcesDocIdRoute,
}

const SourcesRouteWithChildren =
  SourcesRoute._addFileChildren(SourcesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  JobsRoute: JobsRoute,
  LessonsRoute: LessonsRouteWithChildren,
  ProfilesRoute: ProfilesRoute,
  SourcesRoute: SourcesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
